### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by AyomideA-S** [dailydotdev/action-devcard#151]
I keep getting the **Resource not accessible by integration** when trying to set up an action following the instructions here: https://daily.dev/blog/adding-the-daily-devcard-to-your-github-profile?utm_source=webapp&utm_medium=devcard&utm_campaign=devcardguide&utm_id=inapp#using-a-github-action-to-update-your-devcard-automatically .

**Comment by AramLR** [comment]
I have the same issue, I already tried everything. Have you found a solution?

**Comment by AyomideA-S** [comment]
No, not yet.

**Comment by omBratteng** [comment]
@AyomideA-S could you please attach you workflow and your devcard ID, so I could try to debug it?

**Comment by omBratteng** [comment]
> I have the same issue, I already tried everything. Have you found a solution?

@AramLR I do not see a repo on your account, so I can't see your action log

**Comment by omBratteng** [comment]
@AyomideA-S 

Hmm, it seems like your token does not have enough permissions, so it is now allowed to write to the repo.
I will examine and test out why.
```
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
```

**Comment by omBratteng** [comment]
@AyomideA-S Could you also please try to manually dispatch the workflow?
It should be available from the dropdown in this page. https://github.com/AyomideA-S/AyomideA-S/actions/workflows/main.yml
<img width="968" alt="image" src="https://user-images.githubusercontent.com/1681525/167399070-70954c08-5324-41ac-8768-ef0f11bc48ed.png">

**Comment by omBratteng** [comment]
On second thought, I do think it's related to this repository setting.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/1681525/167399573-46a36623-f8b6-4679-882c-9e010c243f13.png">

**Comment by omBratteng** [comment]
You can also add this to the workflow file, if you don't want to change the repo setting

```yaml
permissions:
  contents: write
```

Example commit https://github.com/omBratteng/omBratteng/commit/03058b31b4ad67a076fa1ac4307c5ba8b137da8b

**Comment by omBratteng** [comment]
Closed via 72b6858899f522d8cf3b21b9fd30d28311cb3a3a, updated example yaml to add permissions to the workflow job

**Comment by AyomideA-S** [comment]
> You can also add this to the workflow file, if you don't want to change the repo setting
> 
> ```yaml
> permissions:
>   contents: write
> ```
> 
> Example commit [omBratteng/omBratteng@03058b3](https://github.com/omBratteng/omBratteng/commit/03058b31b4ad67a076fa1ac4307c5ba8b137da8b)

Thank you very much, this fixed the issue.

**Comment by AramLR** [comment]
Thanks! This fixed this issue.
I think it would be great to update [this blog entry](https://daily.dev/blog/adding-the-daily-devcard-to-your-github-profile)

**Comment by omBratteng** [comment]
It should get updated soon @idoshamun

**Comment by idoshamun** [comment]
Yap! Already requested to update this blog :)
