### ISSUE TITLE
Card information not me

### ISSUE THREAD

**Issue by phuocantd** [dailydotdev/action-devcard#165]
https://github.com/phuocantd/phuocantd/blob/devcard/devcard.png

source:https://github.com/phuocantd/phuocantd/blob/main/.github/workflows/devcard.yml
how to display information of me

**Comment by idoshamun** [comment]
Hi @phuocantd,

What do you mean? Is this not your devcard?

**Comment by phuocantd** [comment]
> Hi @phuocantd,
> 
> What do you mean? Is this not your devcard?

yes, I want to show my information
