### ISSUE TITLE
feature: Customisable commiter variable

### ISSUE THREAD

**Issue by centrumek** [dailydotdev/action-devcard#367]
Hello!

I want to have an option to provide extra env vars for this action:
- `committer_name`
- `committer_email`

I can be a volunteer, if maintainers agree on this feat :)

**Comment by centrumek** [comment]
@omBratteng can I implement this feature :)?

**Comment by omBratteng** [comment]
Go ahead 😄

**Comment by centrumek** [comment]
Hi @omBratteng I've created a PR -> https://github.com/dailydotdev/action-devcard/pull/377, you can review and release if it is okey :D

**Comment by omBratteng** [comment]
Closed via #377
